### PR TITLE
GHA-integration initial commit

### PR DESCRIPTION
**Pull request by Agarwal-Shivansh**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
ok to test

**Review by gab-arrobo — APPROVED** [review]
+1

**Comment by gab-arrobo** [comment]
retest this please

**Comment by gab-arrobo** [comment]
@Agarwal-Shivansh, the Jenkins job failed. Please try to test it locally by running `make jenkins-test` and see what is the output you get.

**Comment by gab-arrobo** [comment]
Hi @SeanCondon, do you have any suggestion on how to address the issue with the failing Jenkins job?

**Comment by SeanCondon** [comment]
> Hi @SeanCondon, do you have any suggestion on how to address the issue with the failing Jenkins job?

Hi @gab-arrobo - sorry for the late reply on this - I was on PTO.

I'm seeing the error is with `github.com/favadi/protoc-go-inject-tag` - I don't know why it is a problem - I am able to Get it individually. I will investigate some more.

**Comment by SeanCondon** [comment]
The Dockerfile list of dependencies was quite brittle - with a number being fixed and others getting `latest`. As projects moved on this left incompatibilities. In my commit I have tried to fix to versions that were active around the middle of 2022, when this file was last updated. Some projects have stalled since then and I have left these pointing at latest.

We can try newer versions once we get this baseline working

**Review by SeanCondon — APPROVED** [review]

**Comment by gab-arrobo** [comment]
> > Hi @SeanCondon, do you have any suggestion on how to address the issue with the failing Jenkins job?
> 
> Hi @gab-arrobo - sorry for the late reply on this - I was on PTO.
> 
> I'm seeing the error is with `github.com/favadi/protoc-go-inject-tag` - I don't know why it is a problem - I am able to Get it individually. I will investigate some more.

No problem. I hope you had a good time off

**Pull request merged**
